deps(components): update @scion/components to Angular 15
SchweizerischeBundesbahnen/scion-toolkit pull request #132
Opened 2022-11-23 13:56 UTC by Marcarrian

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our [guidelines](https://github.com/SchweizerischeBundesbahnen/scion-toolkit/blob/master/CONTRIBUTING.md)
- [ ] Tests for the changes have been added
- [ ] Docs have been added or updated

## PR Type
What kind of change does this PR introduce?

- [ ] Fix
- [ ] Feature
- [ ] Documentation
- [ ] Refactoring (changes that neither fixes a bug nor adds a feature)
- [ ] Performance (changes that improve performance)
- [ ] Test (adding missing tests, refactoring tests; no production code change)
- [ ] Chore (other changes like formatting, updating the license, removal of deprecations, etc)
- [x] Deps (changes related to updating dependencies)
- [ ] CI (changes to our CI configuration files and scripts)
- [ ] Revert (revert of a previous commit)
- [ ] Release (publish a new release)
- [ ] Other... Please describe:

## Issue

Issue Number: #112 

## Does this PR introduce a breaking change?

- [x] Yes
- [ ] No

BREAKING CHANGE: Updating `@scion/components` to Angular 15 introduced a breaking change.

To migrate:
- update your application to Angular 15; for detailed migration instructions, refer to https://v15.angular.io/guide/update-to-latest-version;
- update @scion/components to version 15; for detailed migration instructions, refer to https://github.com/SchweizerischeBundesbahnen/scion-toolkit/blob/master/CHANGELOG_COMPONENTS.md;

2022-11-23 16:39 UTC, danielwiehl requested changes

2022-11-24 14:53 UTC, Marcarrian commented on angular.json
> +              "zone.js",
@scion/toolkit uses `fakeAsync` and thus requires zone.js/testing polyfill.

2022-12-07 13:42 UTC, danielwiehl submitted a review, later dismissed

2022-12-07 13:48 UTC, danielwiehl approved these changes

2022-12-07 13:58 UTC, merged